/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Henrique
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLimpar();
    }
    
    private void setLimpar() {
        txtConsumoKwh.setText("");
        cbBandeira.setSelectedIndex(-1);
        lblConsumoMensalSaida.setText("");
        lblTaxaBandieraSaida.setText("");
        lblTaxaIluminacaoSaida.setText("");
        lblValorTotalSaida.setText("");
    }
    
    private boolean IsSelected(JComboBox ComboBox, String Campo) {
        if (ComboBox.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, 
                        "Selecionar uma opção do " + Campo, 
                        "Validação", 
                        JOptionPane.ERROR_MESSAGE);
            ComboBox.requestFocus();
            return false;
        }
        else
            return true;
    }   
    
    private boolean IsFloat(JTextField TextField, String Campo) {
        boolean validar;
        String msg = "";
        try {
            if (TextField.getText().isEmpty()) {
                msg = "Preencher o campo: " ;
                validar = false;
            }
            else {
                float f = Float.parseFloat(TextField.getText());
                validar = true;
            }
        }
        catch(Exception e) {
            msg = "Preencher um valor numerico para o campo: ";
            validar = false;
        }
        
        if (!validar) {
            JOptionPane.showMessageDialog(this, 
                        msg + Campo, 
                        "Validação", 
                        JOptionPane.ERROR_MESSAGE);
            TextField.setText("");
            TextField.requestFocus();        
        }
        
        return validar;          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConsumoKwh = new javax.swing.JLabel();
        txtConsumoKwh = new javax.swing.JTextField();
        lblBandeira = new javax.swing.JLabel();
        cbBandeira = new javax.swing.JComboBox<>();
        lblConsumoMensal = new javax.swing.JLabel();
        lblConsumoMensalSaida = new javax.swing.JLabel();
        lblTaxaBandiera = new javax.swing.JLabel();
        lblTaxaBandieraSaida = new javax.swing.JLabel();
        lblTaxaIluminacao = new javax.swing.JLabel();
        lblTaxaIluminacaoSaida = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        lblValorTotalSaida = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblConsumoKwh.setText("Consumo kw/h");

        lblBandeira.setText("Bandeira");

        cbBandeira.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "Amarelo", "Vermelho" }));
        cbBandeira.setSelectedIndex(-1);

        lblConsumoMensal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConsumoMensal.setText("Consumo mensal:");

        lblConsumoMensalSaida.setText("jLabel4");

        lblTaxaBandiera.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTaxaBandiera.setText("Taxa bandeira:");

        lblTaxaBandieraSaida.setText("jLabel4");

        lblTaxaIluminacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTaxaIluminacao.setText("Taxa Iluminação:");

        lblTaxaIluminacaoSaida.setText("jLabel4");

        lblValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValorTotal.setText("Valor total:");

        lblValorTotalSaida.setText("jLabel4");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorTotalSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTaxaIluminacao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTaxaIluminacaoSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTaxaBandiera, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTaxaBandieraSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblConsumoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblConsumoMensalSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtConsumoKwh)
                    .addComponent(lblBandeira)
                    .addComponent(cbBandeira, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConsumoKwh, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsumoKwh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConsumoKwh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBandeira)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsumoMensal)
                    .addComponent(lblConsumoMensalSaida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxaBandiera)
                    .addComponent(lblTaxaBandieraSaida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxaIluminacao)
                    .addComponent(lblTaxaIluminacaoSaida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotal)
                    .addComponent(lblValorTotalSaida))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnCalcular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        setLimpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        if (IsFloat(txtConsumoKwh, "Consumo kw/h")
                && IsSelected(cbBandeira, "Bandeira")) {                               

                float c = Float.parseFloat(txtConsumoKwh.getText());
                
                //processamento
                float vkwh, tb;
                if (cbBandeira.getSelectedIndex() == 0) {
                    vkwh = 0.736f;
                    tb = 0;
                }
                else if (cbBandeira.getSelectedIndex() == 1) {
                    vkwh = 0.817f;
                    tb = 4.78f;
                }
                else {
                    vkwh = 0.875f;
                    tb = 7.53f;
                }

                float cm = c * vkwh;
                float ti = 31.75f + 0.575f/100.0f * cm;
                float vf =  cm + ti + tb;
                
                lblConsumoMensalSaida.setText("R$ " + String.format("%.2f", cm));
                lblTaxaBandieraSaida.setText("R$ " + String.format("%.2f", tb));
                lblTaxaIluminacaoSaida.setText("R$ " + String.format("%.2f", ti));
                lblValorTotalSaida.setText("R$ " + String.format("%.2f", vf));                
        }       
        else {
            lblConsumoMensalSaida.setText("");
            lblTaxaBandieraSaida.setText("");
            lblTaxaIluminacaoSaida.setText("");
            lblValorTotalSaida.setText("");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbBandeira;
    private javax.swing.JLabel lblBandeira;
    private javax.swing.JLabel lblConsumoKwh;
    private javax.swing.JLabel lblConsumoMensal;
    private javax.swing.JLabel lblConsumoMensalSaida;
    private javax.swing.JLabel lblTaxaBandiera;
    private javax.swing.JLabel lblTaxaBandieraSaida;
    private javax.swing.JLabel lblTaxaIluminacao;
    private javax.swing.JLabel lblTaxaIluminacaoSaida;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblValorTotalSaida;
    private javax.swing.JTextField txtConsumoKwh;
    // End of variables declaration//GEN-END:variables
}
